import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ApifyRunResponse {
  data: {
    id: string;
    status: string;
    defaultDatasetId: string;
  };
}

interface YouTubeVideoData {
  title: string;
  id: string;
  url: string;
  viewCount: number;
  date: string;
  likes: number;
  channelName: string;
  channelUrl: string;
  // Apify returns channelId or externalId — both are checked
  channelId?: string;
  externalId?: string;
  channelUsername?: string;
  channelAvatarUrl?: string;
  channelBannerUrl?: string;
  channelTotalVideos?: number;
  channelTotalViews?: number;
  channelDescription?: string;
  channelJoinedDate?: string;
  numberOfSubscribers: number;
  duration: string;
  thumbnailUrl?: string;
  aboutChannelInfo?: {
    channelDescription?: string;
    channelJoinedDate?: string;
  };
}

/**
 * Robustly extract the YouTube channel ID from an Apify video object.
 * Apify's streamers~youtube-scraper may return it as:
 *   - video.channelId  (most common)
 *   - video.externalId
 *   - parsed from video.channelUrl  e.g. https://www.youtube.com/channel/UCxxxxx
 */
function extractChannelId(video: YouTubeVideoData): string | null {
  if (video.channelId && video.channelId.startsWith('UC')) return video.channelId;
  if (video.externalId && video.externalId.startsWith('UC')) return video.externalId;

  // Fallback: parse from channelUrl
  if (video.channelUrl) {
    const match = video.channelUrl.match(/\/channel\/(UC[a-zA-Z0-9_-]+)/);
    if (match) return match[1];
  }

  return null;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const apifyToken = Deno.env.get('APIFY_API_TOKEN');

    if (!apifyToken) throw new Error('APIFY_API_TOKEN não configurado');

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) throw new Error('Não autorizado');

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) throw new Error('Usuário não autenticado');

    const { channel_id, youtube_url } = await req.json();
    if (!channel_id || !youtube_url) throw new Error('channel_id e youtube_url são obrigatórios');

    console.log(`[scrape] Starting for channel: ${youtube_url}`);

    const { data: channel, error: channelError } = await supabase
      .from('channels')
      .select('id, user_id')
      .eq('id', channel_id)
      .single();

    if (channelError || !channel) throw new Error('Canal não encontrado');
    if (channel.user_id !== user.id) throw new Error('Sem permissão para este canal');

    // --- Start Apify actor ---
    const actorUrl = `https://api.apify.com/v2/acts/streamers~youtube-scraper/runs?token=${apifyToken}`;
    const apifyPayload = {
      downloadSubtitles: false,
      hasCC: false, hasLocation: false, hasSubtitles: false,
      is360: false, is3D: false, is4K: false, isBought: false,
      isHD: false, isHDR: false, isLive: false, isVR180: false,
      maxResultStreams: 0, maxResults: 10, maxResultsShorts: 0,
      preferAutoGeneratedSubtitles: false, saveSubsToKVS: false,
      sortingOrder: 'date',
      startUrls: [{ url: youtube_url }],
    };

    console.log('[scrape] Calling Apify API...');
    const startResponse = await fetch(actorUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(apifyPayload),
    });

    if (!startResponse.ok) {
      const err = await startResponse.text();
      console.error('[scrape] Apify start error:', err);
      throw new Error(`Erro ao iniciar scraper: ${startResponse.status}`);
    }

    const runData: ApifyRunResponse = await startResponse.json();
    const runId = runData.data.id;
    const datasetId = runData.data.defaultDatasetId;
    console.log(`[scrape] Run started: ${runId}, dataset: ${datasetId}`);

    // --- Poll for completion ---
    const maxAttempts = 24;
    let attempts = 0;
    let runStatus = 'RUNNING';

    while (runStatus !== 'SUCCEEDED' && runStatus !== 'FAILED' && attempts < maxAttempts) {
      await new Promise(resolve => setTimeout(resolve, 5000));
      const statusUrl = `https://api.apify.com/v2/actor-runs/${runId}?token=${apifyToken}`;
      const statusResponse = await fetch(statusUrl);
      const statusData = await statusResponse.json();
      runStatus = statusData.data.status;
      attempts++;
      console.log(`[scrape] Status check ${attempts}: ${runStatus}`);
    }

    if (runStatus === 'FAILED') throw new Error('O scraper falhou ao buscar dados do canal');
    if (runStatus !== 'SUCCEEDED') throw new Error('Timeout: O scraper demorou muito para responder');

    // --- Fetch dataset ---
    const datasetUrl = `https://api.apify.com/v2/datasets/${datasetId}/items?token=${apifyToken}`;
    const datasetResponse = await fetch(datasetUrl);
    if (!datasetResponse.ok) throw new Error('Erro ao buscar resultados do dataset');

    const videos: YouTubeVideoData[] = await datasetResponse.json();
    if (!videos || videos.length === 0) throw new Error('Nenhum dado encontrado para este canal');

    console.log(`[scrape] Found ${videos.length} videos`);

    // --- Extract channel info ---
    const firstVideo = videos[0];

    // Log raw fields for diagnosis
    console.log('[scrape] Raw channelId:', firstVideo.channelId);
    console.log('[scrape] Raw externalId:', firstVideo.externalId);
    console.log('[scrape] Raw channelUrl:', firstVideo.channelUrl);

    const resolvedChannelId = extractChannelId(firstVideo);
    console.log('[scrape] Resolved youtube_channel_id:', resolvedChannelId);

    if (!resolvedChannelId) {
      throw new Error(
        `Não foi possível extrair o channel ID do payload. ` +
        `channelId=${firstVideo.channelId}, externalId=${firstVideo.externalId}, channelUrl=${firstVideo.channelUrl}`
      );
    }

    const channelInfo = {
      youtube_channel_id: resolvedChannelId,
      channel_name: firstVideo.channelName,
      username: firstVideo.channelUsername ?? null,
      avatar_url: firstVideo.channelAvatarUrl ?? null,
      banner_url: firstVideo.channelBannerUrl ?? null,
      subscribers: firstVideo.numberOfSubscribers ?? 0,
      total_videos: firstVideo.channelTotalVideos ?? 0,
      total_views: firstVideo.channelTotalViews ?? 0,
      description: firstVideo.aboutChannelInfo?.channelDescription ?? firstVideo.channelDescription ?? null,
      joined_date: firstVideo.aboutChannelInfo?.channelJoinedDate ?? firstVideo.channelJoinedDate ?? null,
    };

    // Calculate monthly views from last 30 days
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    const recentViews = videos
      .filter(v => new Date(v.date) >= thirtyDaysAgo)
      .reduce((sum, v) => sum + (v.viewCount ?? 0), 0);

    console.log('[scrape] channelInfo:', JSON.stringify(channelInfo));
    console.log('[scrape] recentViews (30d):', recentViews);

    // --- Persist to channels table ---
    const { error: updateError } = await supabase
      .from('channels')
      .update({
        youtube_channel_id: channelInfo.youtube_channel_id,
        subscribers: channelInfo.subscribers,
        monthly_views: recentViews,
        avatar_url: channelInfo.avatar_url,
        youtube_connected_at: new Date().toISOString(),
        youtube_username: channelInfo.username,
        youtube_total_videos: channelInfo.total_videos,
        youtube_total_views: channelInfo.total_views,
        youtube_description: channelInfo.description,
        youtube_joined_date: channelInfo.joined_date,
        youtube_banner_url: channelInfo.banner_url,
        last_scraped_at: new Date().toISOString(),
      })
      .eq('id', channel_id);

    if (updateError) {
      console.error('[scrape] Error updating channel:', updateError);
      throw new Error('Erro ao atualizar dados do canal');
    }

    console.log('[scrape] Channel updated with youtube_channel_id:', channelInfo.youtube_channel_id);

    // --- Helper for safe date parsing ---
    const parseSafeDate = (dateStr: string | null | undefined): Date => {
      if (!dateStr) return new Date();
      const d = new Date(dateStr);
      return isNaN(d.getTime()) ? new Date() : d;
    };

    // --- PERSIST VIDEO METRICS ---
    console.log(`[scrape] Persisting ${videos.length} videos into channel_metrics...`);

    const DEFAULT_RPM = 1.5;
    const metricsToInsert = videos.map(video => {
      const videoDate = parseSafeDate(video.date);
      const views = video.viewCount ?? 0;

      return {
        channel_id,
        views,
        rpm: DEFAULT_RPM,
        watch_time_minutes: 0,
        estimated_revenue: (views / 1000) * DEFAULT_RPM,
        last_video_views: views,
        last_video_date: videoDate.toISOString().split('T')[0],
        recorded_at: videoDate.toISOString(),
        video_title: video.title || 'Vídeo importado',
        video_url: video.url || null,
        video_thumbnail: video.thumbnailUrl || null,
      };
    });

    // Clean old metrics to avoid duplicates
    await supabase.from('channel_metrics').delete().eq('channel_id', channel_id);

    const { error: metricsError } = await supabase
      .from('channel_metrics')
      .insert(metricsToInsert);

    if (metricsError) console.error('[scrape] Error inserting metrics:', metricsError);

    // --- Insert top videos as channel contents ---
    const contentsToInsert = videos.slice(0, 10).map(video => {
      const videoDate = parseSafeDate(video.date);
      return {
        channel_id,
        title: video.title,
        status: 'published',
        scheduled_date: videoDate.toISOString().split('T')[0],
      };
    });

    await supabase.from('channel_contents').delete().eq('channel_id', channel_id).eq('status', 'published');
    const { error: contentsError } = await supabase.from('channel_contents').insert(contentsToInsert);
    if (contentsError) console.error('[scrape] Error inserting contents:', contentsError);

    console.log('[scrape] Finished successfully.');

    return new Response(
      JSON.stringify({
        success: true,
        data: {
          channel_name: channelInfo.channel_name,
          youtube_channel_id: channelInfo.youtube_channel_id,
          username: channelInfo.username,
          subscribers: channelInfo.subscribers,
          monthly_views: recentViews,
          total_videos: channelInfo.total_videos,
          total_views: channelInfo.total_views,
          videos_imported: contentsToInsert.length,
          avatar_url: channelInfo.avatar_url,
          banner_url: channelInfo.banner_url,
          description: channelInfo.description,
          joined_date: channelInfo.joined_date,
        },
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('[scrape] Fatal error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Erro desconhecido';
    console.error(`Status 400 reason: ${errorMessage}`);
    return new Response(
      JSON.stringify({
        success: false,
        error: errorMessage,
      }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
